name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Vercel via CLI
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          # Install Vercel CLI and deploy the built `dist` folder to production
          npm i -g vercel
          # Deploy the built `dist` folder directly. Avoid passing unsupported
          # CLI options (older/newer CLI versions may not accept --project/--scope).
          CMD=(npx vercel --prod --yes --token "$VERCEL_TOKEN" ./dist)
          echo "Running: ${CMD[*]}"
          "${CMD[@]}"
